use_frameworks!
platform :ios, '8.0'

target 'SLSkinManage_Example' do
  pod 'SLSkinManage', :path => '../'
  pod 'ZipArchive'
  pod 'AFNetworking'
  target 'SLSkinManage_Tests' do
    inherit! :search_paths
  end
end
